apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollback-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BMithunKumar/helm-files.git
    targetRevision: master
    path: argocd-rollback
    helm:
      valueFiles:
        - ../environments/dev/argocd-rollback.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
