apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-rollback.fullname" . }}
  labels:
    {{- include "argocd-rollback.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.restPort }}
      targetPort: {{ .Values.service.restTargetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-rollback.selectorLabels" . | nindent 4 }}
